
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import Project.connectionProvider;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class AddNewPatient extends javax.swing.JFrame {

    static Connection conn;
    static Statement st;
    static String sql;
    PreparedStatement ps;
    
    public AddNewPatient() {
        conn = new Database().setConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Close = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TFPatientId = new javax.swing.JTextField();
        TFName = new javax.swing.JTextField();
        TFContact = new javax.swing.JTextField();
        TFAge = new javax.swing.JTextField();
        TFBloodGroup = new javax.swing.JTextField();
        TFGender = new javax.swing.JComboBox<>();
        TFAdress = new javax.swing.JTextField();
        TFDiseassedEarlier = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Save = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 72, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 112, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Contact No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 155, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 195, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Blood Group");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 284, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 327, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Major Diseassed Suffered Earlier ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 367, -1, -1));

        TFPatientId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TFPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPatientIdActionPerformed(evt);
            }
        });
        getContentPane().add(TFPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 66, 300, -1));

        TFName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(TFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 109, 300, -1));

        TFContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(TFContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 152, 302, -1));

        TFAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(TFAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 201, 302, -1));

        TFBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(TFBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 281, 302, -1));

        TFGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TFGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Gender--", "Male", "Female" }));
        TFGender.setPreferredSize(new java.awt.Dimension(56, 27));
        TFGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFGenderActionPerformed(evt);
            }
        });
        getContentPane().add(TFGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 236, 120, -1));

        TFAdress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TFAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAdressActionPerformed(evt);
            }
        });
        getContentPane().add(TFAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 324, 302, -1));

        TFDiseassedEarlier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TFDiseassedEarlier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDiseassedEarlierActionPerformed(evt);
            }
        });
        getContentPane().add(TFDiseassedEarlier, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 398, 423, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADD PATIENT ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 100, -1));

        Save.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient background.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_CloseActionPerformed

    private void TFAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAdressActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

          String pasien_id = TFPatientId.getText();
  // int pasien_id = Integer.parseInt(TFPatientId.getText());
        String nama =  TFName.getText();
        //String kontak = TFContact.getText();
       // String umur = TFAge.getText();
       String kontak = TFContact.getText();
       //int kontak = Integer.parseInt(TFContact.getText());
        int umur = Integer.parseInt(TFAge.getText());
        String kelamin = (String)TFGender.getSelectedItem();
        String goldar = TFBloodGroup.getText();
        String alamat = TFAdress.getText();
        String penyakitBawaan =TFDiseassedEarlier.getText();
        
        
         try{
          Connection con = connectionProvider.getCon();
          Statement st = con.createStatement();
          st.executeUpdate( "INSERT INTO addpatienttable VALUES('"+pasien_id+"','"+nama+"','"+kontak+"','"+umur+"','"+
                  kelamin+"','"+goldar+"','"+alamat+"','"+penyakitBawaan+"')");
//          sql = "INSERT INTO addpatienttable VALUES (?,?,?,?,?,?,?,?)";
//          ps = conn.prepareStatement(sql);
//          ps.setInt(1, pasien_id);
//          ps.setString(2, nama);
//          ps.setInt(3, kontak); 
//          ps.setInt(4, umur);
//          ps.setString(5, kelamin);
//          ps.setString(6, goldar);
//          ps.setString(7, alamat);
//          ps.setString(8, penyakitBawaan);
//          
          
         // int rt = ps.executeUpdate();
          JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!","Informasi",JOptionPane.INFORMATION_MESSAGE);
          this.dispose();
          AddNewPatient tambah_pasien = new AddNewPatient();
          tambah_pasien.setVisible(true);
    }                                              
      catch(Exception e ){
          System.out.println("Please enter data in correct format " + e.getMessage());
      }
        
        
    }//GEN-LAST:event_SaveActionPerformed

    private void TFDiseassedEarlierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDiseassedEarlierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFDiseassedEarlierActionPerformed

    private void TFPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPatientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPatientIdActionPerformed

    private void TFGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFGenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Close;
    private javax.swing.JToggleButton Save;
    private javax.swing.JTextField TFAdress;
    private javax.swing.JTextField TFAge;
    private javax.swing.JTextField TFBloodGroup;
    private javax.swing.JTextField TFContact;
    private javax.swing.JTextField TFDiseassedEarlier;
    private javax.swing.JComboBox<String> TFGender;
    private javax.swing.JTextField TFName;
    private javax.swing.JTextField TFPatientId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
